### ISSUE TITLE
can't work

### ISSUE THREAD

**Issue by endlessV** [chunlinhan/WiFiRM04#26]
hello, i am use mega2560 and pin rm04 same u:
RM04 pins    mega2560 pins
UART_RX(pin 20) TX1 (pin 18)
UART_TX(pin 21) RX1 (pin 19)
RXD(pin 22) TX2(pin 16)
TXD(pin 26) RX2(pin 17)
VCC (pin 1, 28) 5V out
pin 10     pin 21
GND GND

but it still 
[C:\Users\91072206\Documents\Arduino\libraries\WiFiRM04\utility\at_drv.cpp::119]-I-Echo No resp
[C:\Users\91072206\Documents\Arduino\libraries\WiFiRM04\utility\at_drv.cpp::936]-I-Can't switch to at mode 

:(

**Comment by gohoho** [comment]
Hi!
I had the same issue with arduino IDE version 1.6, after installing older version (1.0.6) everything works out of the box.

**Comment by endlessV** [comment]
thanks, it nearly work. but still can't switch to at mode :p
I use example ScanNetwork and here result: 

[C:\Users\MrV\Documents\Arduino\libraries\WiFiRM04\utility\at_drv.cpp::482]-I-Can't switch to at mode
[C:\Users\MrV\Documents\Arduino\libraries\WiFiRM04\utility\at_drv.cpp::966]-I-Can't switch to at mode
MAC: 0:0:0:0:0:0
Scanning available networks...
** Scan Networks **
[C:\Users\MrV\Documents\Arduino\libraries\WiFiRM04\utility\at_drv.cpp::1879]-I-Can't switch to at mode
[C:\Users\MrV\Documents\Arduino\libraries\WiFiRM04\utility\at_drv.cpp::1879]-I-Can't switch to at mode
[C:\Users\MrV\Documents\Arduino\libraries\WiFiRM04\utility\at_drv.cpp::1879]-I-Can't switch to at mode
[C:\Users\MrV\Documents\Arduino\libraries\WiFiRM04\utility\at_drv.cpp::1879]-I-Can't switch to at mode
[C:\Users\MrV\Documents\Arduino\libraries\WiFiRM04\utility\at_drv.cpp::1879]-I-Can't switch to at mode
[C:\Users\MrV\Documents\Arduino\libraries\WiFiRM04\utility\at_drv.cpp::1879]-I-Can't switch to at mode
[C:\Users\MrV\Documents\Arduino\libraries\WiFiRM04\utility\at_drv.cpp::1879]-I-Can't switch to at mode
[C:\Users\MrV\Documents\Arduino\libraries\WiFiRM04\utility\at_drv.cpp::1879]-I-Can't switch to at mode
[C:\Users\MrV\Documents\Arduino\libraries\WiFiRM04\utility\at_drv.cpp::1879]-I-Can't switch to at mode
[C:\Users\MrV\Documents\Arduino\libraries\WiFiRM04\utility\at_drv.cpp::1879]-I-Can't switch to at mode
number of available networks:0

**Comment by gohoho** [comment]
Maybe uart baudrate is the issue? By default module works on 115200 baud, but library configured to work on 38400.

**Comment by endlessV** [comment]
thanks again, i forgot fix it when copy paste lib after uninstall IDE 1.6
it work

**Comment by gohoho** [comment]
Great! I am glad I helped you!
Now this could be closed?

**Comment by j5566n2002** [comment]
Sorry. I used to  38400 baud
but it still does not work

**Comment by kikoalencar** [comment]
I have the same problem. What shoul I do?
