### ISSUE TITLE
Escape pin problem

### ISSUE THREAD

**Issue by sunweylee** [chunlinhan/WiFiRM04#33]
Hi chunlin:

   I'm using your library in uno to build some monitor system prototype with hlkrm04(with shield), during implement the wifi shield can't enter into AT mode. It seems that your lib using pin 21(Mega), but Uno is different one. Pin 21 in mega seems SCL, is this same in UNO?

**Comment by chunlinhan** [comment]
Hi,

You could use any unused GPIO pin of UNO as ESCAPE_PIN.
